View(Titanic)
x=c(8,5,-10,7,13,-2,7,6,-3,3,5,12,11,-2,3,-4,6,7,6,-5)
boxplot(x,horizontal = T)
points(mean(x),1,col = 3,pch = 19)
points(mean(x),5,col = 3,pch = 19)
stripchart(x,method="jitter",add = T,col = "blue")
boxplot(chickwts$weight ~ chickwts$feed)
View(chickwts)
stripchart(chickwts$weight~chickwts$feed,vertical = T,method = "jitter",add = T,col=1:length(chickwts$feed))

